namespace Birds.Shared.Localization;

public static partial class AppText
{
    private static IReadOnlyDictionary<string, string> BuildEnglish()
    {
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Language.Russian"] = "Russian",
            ["Language.English"] = "English",

            ["Nav.AddBird"] = "Add bird",
            ["Nav.Archive"] = "Archive",
            ["Nav.Statistics"] = "Statistics",
            ["Nav.Settings"] = "Settings",

            ["Main.Header.AddBird.Title"] = "Add bird",
            ["Main.Header.AddBird.Subtitle"] = "A new entry with basic validation and a clean input form.",
            ["Main.Header.Archive.Title"] = "Bird archive",
            ["Main.Header.Archive.Subtitle"] = "Search, filter and edit existing entries.",
            ["Main.Header.Statistics.Title"] = "Statistics",
            ["Main.Header.Statistics.Subtitle"] = "Overview by species, dates and key metrics.",
            ["Main.Header.Settings.Title"] = "Settings",
            ["Main.Header.Settings.Subtitle"] = "Preferences for the interface and application behaviour.",
            ["Main.Header.Default.Title"] = "Birds",
            ["Main.Header.Default.Subtitle"] = "The application's workspace.",

            ["AddBird.SpeciesLabel"] = "Bird species",
            ["AddBird.ArrivalLabel"] = "Arrival date",
            ["AddBird.DescriptionLabel"] = "Description",
            ["AddBird.DescriptionHint"] = "Description is optional. Up to 200 characters.",
            ["AddBird.OneTimeTitle"] = "One-time keeping",
            ["AddBird.OneTimeHint"] =
                "If the bird arrived and left on the same day, the departure date will be filled automatically.",
            ["AddBird.Save"] = "Save entry",

            ["Bird.CreatedLabel"] = "Created: ",
            ["Bird.UpdatedLabel"] = "Updated: ",
            ["Bird.DaysSuffix"] = "days",
            ["Bird.ArrivalMeta"] = "Arrived",
            ["Bird.DepartureMeta"] = "Departed",
            ["Bird.DurationMeta"] = "Duration",
            ["Bird.StatusLabel"] = "Status",
            ["Bird.StatusAlive"] = "Alive",
            ["Bird.StatusDead"] = "Dead",
            ["Bird.NoDescription"] = "No description added.",
            ["Bird.Action.Edit"] = "Edit entry",
            ["Bird.Action.Delete"] = "Delete entry",
            ["Bird.Action.ConfirmDelete"] = "Confirm deletion",
            ["Bird.Action.CancelDelete"] = "Cancel deletion",
            ["Bird.Action.Save"] = "Save changes",
            ["Bird.Action.CancelEdit"] = "Cancel editing",

            ["BirdList.CountLabel"] = "Birds: ",
            ["BirdList.CountTitle"] = "Birds",
            ["BirdList.SearchPlaceholder"] = "Search by species, date or note",
            ["BirdList.Retry"] = "Retry",
            ["BirdList.EmptyTitle"] = "Nothing found",
            ["BirdList.EmptyDescription"] = "Try changing the search or filter.",
            ["BirdList.Loading"] = "Loading archive...",
            ["BirdList.Filter.All"] = "Show all",
            ["BirdList.Filter.Alive"] = "Show alive only",
            ["BirdList.Filter.Dead"] = "Dead only",
            ["BirdList.Filter.Released"] = "Released",

            ["Statistics.Title"] = "Bird statistics",
            ["Statistics.Year"] = "Year:",
            ["Statistics.AllYears"] = "All years",
            ["Statistics.TotalBirdsLabel"] = "Captured total: ",
            ["Statistics.ReleasedLabel"] = "Released: ",
            ["Statistics.KilledLabel"] = "Destroyed: ",
            ["Statistics.TopMonthLabel"] = "Most productive month: ",
            ["Statistics.TopWeekLabel"] = "Most productive week: ",
            ["Statistics.TopDayLabel"] = "Most productive day: ",
            ["Statistics.LongestBreakLabel"] = "Longest break: ",
            ["Statistics.OverviewTitle"] = "Statistics overview",
            ["Statistics.FilterSummary.All"] =
                "Showing the full archive picture. You can narrow it down to a single year at any time.",
            ["Statistics.FilterSummary.Year"] = "Showing statistics only for {0}.",
            ["Statistics.Card.Total"] = "Records in scope",
            ["Statistics.Card.Alive"] = "Currently under care",
            ["Statistics.Card.Released"] = "Released",
            ["Statistics.Card.Dead"] = "Dead",
            ["Statistics.Card.ArrivalsLast30Days"] = "Arrived in 30 days",
            ["Statistics.Card.DeparturesLast30Days"] = "Departed in 30 days",
            ["Statistics.Card.PeakConcurrent"] = "Peak birds in care",
            ["Statistics.Card.MedianKeeping"] = "Median keeping",
            ["Statistics.Section.Species.Title"] = "Species distribution",
            ["Statistics.Section.Species.Description"] = "Which species appear most often in the current scope.",
            ["Statistics.Section.Highlights.Title"] = "Highlights",
            ["Statistics.Section.Highlights.Description"] =
                "A quick readout of peak periods and average keeping duration.",
            ["Statistics.Section.OverviewBreakDescription"] = "The most noticeable gap without new archive arrivals.",
            ["Statistics.Section.Months.Title"] = "Arrivals by month",
            ["Statistics.Section.Months.Description"] = "Monthly activity inside the current scope.",
            ["Statistics.Section.Departures.Title"] = "Departures by month",
            ["Statistics.Section.Departures.Description"] =
                "How departures are distributed across months inside the current scope.",
            ["Statistics.Section.Years.Title"] = "Year overview",
            ["Statistics.Section.Years.Description"] = "How many records belong to each year across the whole archive.",
            ["Statistics.Section.Keeping.Title"] = "Maximum keeping duration",
            ["Statistics.Section.Keeping.Description"] =
                "The longest keeping period for each species in the current scope.",
            ["Statistics.Highlight.AverageKeeping"] = "Average keeping duration",
            ["Statistics.Highlight.TopMonth"] = "Peak month",
            ["Statistics.Highlight.TopWeek"] = "Peak week",
            ["Statistics.Highlight.TopDay"] = "Peak day",
            ["Statistics.Highlight.LongestBreak"] = "Longest quiet break",
            ["Statistics.Highlight.LongestActiveKeeping"] = "Longest active case",
            ["Statistics.AverageKeepingValue"] = "Average of {0} days",
            ["Statistics.MedianKeepingValue"] = "Median of {0} days",
            ["Statistics.LongestActiveKeepingValue"] = "{0} — {1} days since {2}",
            ["Statistics.EmptyTitle"] = "No statistics yet",
            ["Statistics.EmptyDescription"] =
                "There are no records in this scope yet. Try another year or add birds to the archive.",
            ["Statistics.Tab.Overview"] = "Overview",
            ["Statistics.Tab.Distribution"] = "Distribution",
            ["Statistics.Tab.Keeping"] = "Keeping",
            ["Statistics.Tab.BySpecies"] = "By species",
            ["Statistics.Tab.ByYears"] = "By years",
            ["Statistics.Tab.ByMonths"] = "By months",
            ["Statistics.Tab.ByKeepingDuration"] = "By keeping duration",
            ["Statistics.Loading"] = "Loading...",
            ["Statistics.CountBirds"] = "{0} birds",
            ["Statistics.LongestBreakValue"] = "{0} days without captures (between {1} and {2})",

            ["Settings.Title"] = "Settings",
            ["Settings.Subtitle"] = "A hub for user preferences. Changes are saved automatically.",
            ["Settings.Interface.Title"] = "Interface",
            ["Settings.Interface.Description"] = "Manage language, theme and the base interaction behaviour here.",
            ["Settings.LanguageLabel"] = "Interface language",
            ["Settings.ThemeLabel"] = "Application theme",
            ["Settings.DateFormatLabel"] = "Date format",
            ["Settings.Theme.Graphite"] = "Graphite",
            ["Settings.Theme.Steel"] = "Steel",
            ["Settings.DateFormat.DayMonthYear"] = "31.12.2026",
            ["Settings.DateFormat.MonthDayYear"] = "12/31/2026",
            ["Settings.DateFormat.YearMonthDay"] = "2026-12-31",
            ["Settings.Notifications.Title"] = "Notifications",
            ["Settings.Notifications.Description"] =
                "You can keep notification history while hiding the distracting unread indicator.",
            ["Settings.NotificationBadgeLabel"] = "Show unread notification badge",
            ["Settings.SyncIndicatorLabel"] = "Show sync status chip",
            ["Settings.AutoExportLabel"] = "Automatic snapshot export",
            ["Settings.SyncStatusLabel"] = "Cloud sync status",
            ["Settings.Data.Title"] = "Data",
            ["Settings.Data.Description"] =
                "Export the current snapshot manually or import a JSON file produced by the application.",
            ["Settings.ExportPathLabel"] = "Export location",
            ["Settings.ExportFileButton"] = "Open file",
            ["Settings.ExportFolderButton"] = "Open folder",
            ["Settings.ExportPathButton"] = "Change path",
            ["Settings.ExportLabel"] = "Export data",
            ["Settings.ExportButton"] = "Export",
            ["Settings.ImportModeLabel"] = "Import mode",
            ["Settings.ImportMode.Merge"] = "Merge with current data",
            ["Settings.ImportMode.Replace"] = "Replace current data completely",
            ["Settings.ImportLabel"] = "Import data",
            ["Settings.ImportButton"] = "Import",
            ["Settings.Data.ExportHint"] = "Export location: {0}",
            ["Settings.Data.ExportActionHint"] = "Exports the current snapshot to the selected JSON file.",
            ["Settings.Data.ImportHint.Merge"] =
                "Import merges records by Id: new entries are added, matching ones are updated, and local records outside the file remain untouched.",
            ["Settings.Data.ImportHint.Replace"] =
                "Import replaces the current archive with the snapshot from the file. Local records missing from the file will be removed.",
            ["Settings.ResetTitle"] = "Reset to defaults",
            ["Settings.ResetDescription"] = "Useful when you want to quickly return to the default interface settings.",
            ["Settings.ResetButton"] = "Reset",
            ["Settings.Danger.Title"] = "Danger zone",
            ["Settings.Danger.Description"] =
                "Irreversible data actions. It is best to export a backup before using them.",
            ["Settings.Danger.ClearTitle"] = "Clear all bird records",
            ["Settings.Danger.ClearDescription"] =
                "Removes every bird record from the archive while keeping the database structure and application settings intact.",
            ["Settings.Danger.ClearButton"] = "Clear archive",
            ["Settings.Danger.ClearConfirm"] = "Yes, clear archive",
            ["Settings.Danger.ResetTitle"] = "Reset local SQLite database",
            ["Settings.Danger.ResetDescription"] =
                "Recreates the local database from scratch. Use this only when you want a complete local reset.",
            ["Settings.Danger.ResetButton"] = "Reset database",
            ["Settings.Danger.ResetConfirm"] = "Yes, reset database",
            ["Settings.Danger.Cancel"] = "Cancel",
            ["Settings.Danger.ConfirmClearHint"] = "Confirm clearing the archive. This action cannot be undone.",
            ["Settings.Danger.ConfirmResetHint"] =
                "Confirm resetting the local SQLite database. All records will be removed without recovery.",
            ["Settings.Danger.ResetUnavailable"] =
                "Full database reset is available only when the application uses local SQLite.",
            ["Settings.LanguageHint.Russian"] =
                "Russian is now used for the interface, notifications and validation messages.",
            ["Settings.LanguageHint.English"] =
                "English is now used for the interface, notifications and validation messages.",
            ["Settings.ThemeHint.Graphite"] = "A restrained graphite palette with a neutral accent.",
            ["Settings.ThemeHint.Steel"] = "A colder steel palette with a clearer blue tone.",
            ["Settings.DateFormatHint.DayMonthYear"] =
                "Day comes first, then month and year. Good for a familiar local reading order.",
            ["Settings.DateFormatHint.MonthDayYear"] =
                "Month comes first, then day and year. Useful if you prefer the US-style order.",
            ["Settings.DateFormatHint.YearMonthDay"] =
                "Year comes first, then month and day. Works well for a strict sortable format.",
            ["Settings.ImportModeHint.Merge"] =
                "Safe mode: the import enriches the archive and updates matching records without touching the rest.",
            ["Settings.ImportModeHint.Replace"] =
                "Snapshot restore mode: the current archive will be synchronized with the file and extra local records will be removed.",
            ["Settings.NotificationsHint.Enabled"] =
                "The unread badge will be shown next to the notification center button.",
            ["Settings.NotificationsHint.Disabled"] =
                "The red unread badge is hidden, but the notification history stays available.",
            ["Settings.SyncIndicatorHint.Enabled"] =
                "The synchronization chip will be shown next to the notification center button.",
            ["Settings.SyncIndicatorHint.Disabled"] =
                "The synchronization chip is hidden, but the detailed status remains available in settings.",
            ["Settings.SyncIndicatorHint.Enabled"] =
                "The synchronization status chip will be shown next to the notification center button.",
            ["Settings.SyncIndicatorHint.Disabled"] =
                "The synchronization status chip is hidden, but the detailed status remains available in settings.",
            ["Settings.AutoExportHint.Enabled"] =
                "After successful changes and on application shutdown the export snapshot will be refreshed automatically.",
            ["Settings.AutoExportHint.Disabled"] =
                "Auto-export is disabled. The snapshot will only be updated manually.",
            ["Settings.SyncStatus.Disabled"] = "Local only",
            ["Settings.SyncStatus.Syncing"] = "Syncing",
            ["Settings.SyncStatus.Synced"] = "Synced",
            ["Settings.SyncStatus.Paused"] = "Paused",
            ["Settings.SyncStatus.Offline"] = "Offline",
            ["Settings.SyncStatus.Error"] = "Error",
            ["Settings.SyncStatusHint.Disabled"] =
                "Remote synchronization is not configured. The application is using only the local SQLite store.",
            ["Settings.SyncStatusHint.Syncing"] =
                "Local changes are currently being synchronized with the remote backend.",
            ["Settings.SyncStatusHint.SyncingWithLastSuccess"] =
                "Synchronization is in progress. The last successful exchange was at {0}.",
            ["Settings.SyncStatusHint.Synced"] = "The local archive is synchronized with the remote backend.",
            ["Settings.SyncStatusHint.SyncedWithTimestamp"] = "Last successful sync: {0}.",
            ["Settings.SyncStatusHint.Paused"] = "Automatic synchronization is paused.",
            ["Settings.SyncStatusHint.PausedWithLastSuccess"] =
                "Automatic synchronization is paused. The last successful exchange was at {0}.",
            ["Settings.SyncStatusHint.Offline"] =
                "The remote backend is currently unavailable. Local changes will stay queued and synchronize automatically when the connection returns.",
            ["Settings.SyncStatusHint.Error"] =
                "The latest synchronization attempt failed. Local changes will stay queued until the next successful attempt.",
            ["Settings.SyncStatusHint.PendingCount"] = "Queued local changes: {0}.",
            ["Settings.SyncStatusHint.LastError"] = "Latest detail: {0}",
            ["Settings.SyncMeta.PendingLabel"] = "Pending",
            ["Settings.SyncMeta.PendingNone"] = "None",
            ["Settings.SyncMeta.LastSuccessLabel"] = "Last success",
            ["Settings.SyncMeta.Never"] = "Never",
            ["Settings.SyncMeta.RecentActivityLabel"] = "Recent activity",
            ["Settings.SyncMeta.RecentActivityEmpty"] =
                "No synchronization events have been recorded in this session yet.",
            ["Settings.SyncMeta.RecentActivityExpand"] = "Show",
            ["Settings.SyncMeta.RecentActivityCollapse"] = "Hide",
            ["Settings.SyncAction.SyncNow"] = "Sync now",
            ["Settings.SyncAction.Pause"] = "Pause",
            ["Settings.SyncAction.Resume"] = "Resume",
            ["Settings.SyncAction.UploadTitle"] = "Upload local snapshot to remote",
            ["Settings.SyncAction.UploadDescription"] =
                "Replaces the remote backend snapshot with the current state of the local SQLite archive. Existing remote-only data will be overwritten.",
            ["Settings.SyncAction.UploadButton"] = "Upload snapshot",
            ["Settings.SyncAction.UploadConfirmHint"] =
                "Confirm uploading the current local snapshot. The remote backend will be fully replaced with the current local SQLite data.",
            ["Settings.SyncAction.UploadConfirm"] = "Yes, upload local snapshot",
            ["Settings.SyncAction.RedownloadTitle"] = "Re-download remote snapshot",
            ["Settings.SyncAction.RedownloadDescription"] =
                "Replaces the local SQLite snapshot with the current state from the remote backend. Unsynced local changes will be lost.",
            ["Settings.SyncAction.RedownloadButton"] = "Re-download",
            ["Settings.SyncAction.RedownloadConfirmHint"] =
                "Confirm re-downloading the remote snapshot. The local SQLite snapshot will be fully replaced with the current remote data.",
            ["Settings.SyncAction.RedownloadConfirm"] = "Yes, re-download snapshot",
            ["Settings.SyncRecent.SyncedProcessed"] = "Processed changes: {0}.",
            ["Settings.SyncRecent.SyncedIdle"] = "The synchronization cycle completed without new changes.",
            ["Settings.SyncRecent.Paused"] = "Automatic synchronization is paused.",
            ["Settings.SyncRecent.Offline"] = "The remote backend is temporarily unavailable.",
            ["Settings.SyncRecent.Error"] = "The latest synchronization attempt failed.",
            ["Settings.SyncRecent.LocalOnly"] = "The application is running in local-only mode.",
            ["Notification.CenterTitle"] = "Notifications",
            ["Notification.UnreadLabel"] = "Unread: ",
            ["Notification.Clear"] = "Clear",
            ["Notification.EmptyTitle"] = "Nothing here yet",
            ["Notification.EmptyDescription"] =
                "The history of actions and important application messages will appear here.",
            ["Notification.New"] = "New",
            ["Notification.Type.Info"] = "Info",
            ["Notification.Type.Success"] = "Success",
            ["Notification.Type.Warning"] = "Warning",
            ["Notification.Type.Error"] = "Error",
            ["Notification.Title.Info"] = "Information",
            ["Notification.Title.Success"] = "Success",
            ["Notification.Title.Warning"] = "Warning",
            ["Notification.Title.Error"] = "Error",
            ["Notification.QuickStatus.Success"] = "The latest operation completed successfully",
            ["Notification.QuickStatus.Error"] = "The latest operation failed",
            ["Notification.UndoDelete"] = "Undo",
            ["Notification.UndoDelete.ToolTip"] = "Undo deleting this entry",

            ["Exception.Source.UiDispatcher"] = "UI Dispatcher",
            ["Exception.Source.AppDomain"] = "AppDomain",
            ["Exception.Source.UnobservedTask"] = "Unobserved Task",
            ["Exception.InvalidOperation"] =
                "ExceptionHandlingBehavior can only handle responses of type Result or Result<T>. Actual type: {0}",
            ["Exception.NotFound"] = "{0} with key '{1}' was not found.",
            ["Exception.ValidationFailure"] = "Validation error: {0}",
            ["Exception.NotFoundFailure"] = "Not found: {0}",
            ["Exception.UnexpectedFailure"] = "Unexpected error: {0}",
            ["Exception.OperationCanceled"] = "{0}: The operation was canceled.",
            ["Exception.Timeout"] = "{0}: The operation has timed out.",
            ["Exception.Network"] = "{0}: A network error occurred. Check your internet connection.",
            ["Exception.DatabaseConnection"] = "{0}: Failed to connect to the database.",
            ["Exception.Unexpected"] = "{0}: An unexpected error has occurred.",

            ["Info.LoadingBirdData"] = "Loading bird data...",
            ["Info.LoadedSuccessfully"] = "Bird data loaded successfully.",
            ["Info.NoBirdRecordsYet"] = "No bird records yet. Add your first bird to get started.",
            ["Info.ReloadingBirdData"] = "Reloading bird data...",
            ["Info.AddingBird"] = "Adding bird...",
            ["Info.UpdatingBird"] = "Updating bird...",
            ["Info.UpdatedBird"] = "Bird updated successfully!",
            ["Info.DeletingBird"] = "Deleting bird...",
            ["Info.DeletedBird"] = "Bird deleted successfully!",
            ["Info.DeleteRestored"] = "Deletion was canceled. The record was restored.",
            ["Info.BirdAdded"] = "Bird added successfully!",
            ["Info.ToThisDay"] = "to this day",
            ["Info.LoadFailed"] = "Attempt {0} to load birds failed. Retrying in {1}s.",
            ["Info.AutoExportSucceeded"] = "Auto-export succeeded. Path: {0}",
            ["Info.ExportSucceeded"] = "Export completed. Path: {0}",
            ["Info.ImportMergedSucceeded"] = "Import completed. Processed: {0}, added: {1}, updated: {2}.",
            ["Info.ImportReplacedSucceeded"] =
                "Snapshot restored. Processed: {0}, added: {1}, updated: {2}, removed: {3}.",
            ["Info.BirdRecordsCleared"] = "Archive cleared. Records removed: {0}.",
            ["Info.LocalDatabaseReset"] = "Local database has been reset.",
            ["Info.RemoteSnapshotUploaded"] = "The remote backend snapshot was replaced with the current local SQLite data.",
            ["Info.RemoteSnapshotRedownloaded"] = "The local SQLite snapshot was restored from the remote backend.",
            ["Info.SyncConflictResolved"] = "Cloud sync resolved {0} conflict(s) using the newer remote version.",

            ["Error.BirdLoadFailed"] =
                "Failed to load bird data from the database.\nPlease check your connection or restart the application.",
            ["Error.UnknownError"] = "Unknown error.",
            ["Error.UnexpectedError"] = "Unexpected error.",
            ["Error.CannotSaveBird"] = "Unable to save bird!",
            ["Error.CannotDeleteBird"] = "Unable to delete bird!",
            ["Error.CannotUpdateBird"] = "Unable to update bird!",
            ["Error.RequestCannotBeNull"] = "Request cannot be null.",
            ["Error.QueryCannotBeNull"] = "Query cannot be null.",
            ["Error.ConnectionStringNotFound"] = "Database connection string not found.",
            ["Error.ConnectionStringNotFoundFor"] = "Database connection string not found. Expected one of: {0}.",
            ["Error.InvalidDatabaseProvider"] = "Unsupported database provider '{0}'. Use 'Sqlite' or 'Postgres'.",
            ["Error.InvalidDatabaseSeedingMode"] =
                "Unsupported database seeding mode '{0}'. Use 'None', 'SeedIfEmpty' or 'RecreateAndSeed'.",
            ["Error.ImportPathCannotBeEmpty"] = "The import file path is missing.",
            ["Error.ImportFileNotFound"] = "Import file not found: {0}",
            ["Error.ImportPayloadCannotBeNull"] = "The imported data payload is missing.",
            ["Error.InvalidImportFileFormat"] =
                "Unable to parse the import file. A Birds application JSON export was expected.",
            ["Error.UnsupportedImportVersion"] = "The import file uses an unsupported version: {0}.",
            ["Error.ImportContainsDuplicateIds"] = "The import file contains a duplicate Id: {0}.",
            ["Error.InvalidImportedBirdName"] = "Import aborted: unknown bird name '{0}'.",
            ["Error.ImportFailed"] = "Unable to import bird data.",
            ["Error.ExportFailed"] = "Unable to export bird data.",
            ["Error.CannotOpenExportFile"] = "Unable to open the export file.",
            ["Error.CannotOpenExportFolder"] = "Unable to open the export folder.",
            ["Error.CannotClearBirdRecords"] = "Unable to clear bird records.",
            ["Error.CannotResetLocalDatabase"] = "Unable to reset the local database.",
            ["Error.CannotUploadLocalSnapshotToRemote"] =
                "Unable to replace the remote backend snapshot with the local SQLite data.",
            ["Error.CannotRedownloadRemoteSnapshot"] =
                "Unable to restore the local snapshot from the remote backend.",
            ["Error.FailedToDisplayErrorNotification"] = "Failed to display error notification",
            ["Error.StartupErrorTitle"] = "Startup error",
            ["Error.StartupError"] = "An error occurred during application startup:\n{0}",
            ["Error.ShutdownWarningTitle"] = "Shutdown warning",
            ["Error.ShutdownError"] = "Error during application shutdown:\n{0}",

            ["Validation.UnselectedBird"] = "Select a bird species from the list.",
            ["Validation.LongDescription"] = "Description is too long. Maximum is 200 characters.",
            ["Validation.DateIsNotSpecified"] = "Specify a date.",
            ["Validation.InvalidDateRange"] = "The date must be between {0:dd-MM-yyyy} and {1:dd-MM-yyyy}.",
            ["Validation.DateIsNotValid"] = "Specify a valid date.",
            ["Validation.DateCannotBeInTheFuture"] = "The date cannot be in the future (no later than {0:dd-MM-yyyy}).",
            ["Validation.DepartureLaterThenArrival"] =
                "Departure date cannot be earlier than arrival date ({0:dd-MM-yyyy}).",

            ["BirdName.Воробей"] = "Sparrow",
            ["BirdName.Щегол"] = "Goldfinch",
            ["BirdName.Амадин"] = "Amadin",
            ["BirdName.Дубонос"] = "Hawfinch",
            ["BirdName.Большак"] = "Great tit",
            ["BirdName.Гайка"] = "Black-capped chickadee",
            ["BirdName.Поползень"] = "Nuthatch",
            ["BirdName.Unknown"] = "Unknown"
        };
    }
}
