using System.Globalization;

namespace Birds.Shared.Localization
{
    public static class AppText
    {
        private static readonly IReadOnlyDictionary<string, string> Russian = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Language.Russian"] = "Русский",
            ["Language.English"] = "English",

            ["Nav.AddBird"] = "Добавить птицу",
            ["Nav.Archive"] = "Архив",
            ["Nav.Statistics"] = "Статистика",
            ["Nav.Settings"] = "Настройки",

            ["Main.Header.AddBird.Title"] = "Добавление птицы",
            ["Main.Header.AddBird.Subtitle"] = "Новая запись с базовой валидацией и чистой формой ввода.",
            ["Main.Header.Archive.Title"] = "Архив птиц",
            ["Main.Header.Archive.Subtitle"] = "Поиск, фильтрация и редактирование существующих записей.",
            ["Main.Header.Statistics.Title"] = "Статистика",
            ["Main.Header.Statistics.Subtitle"] = "Сводка по видам, датам и ключевым метрикам.",
            ["Main.Header.Settings.Title"] = "Настройки",
            ["Main.Header.Settings.Subtitle"] = "Пользовательские предпочтения интерфейса и поведения приложения.",
            ["Main.Header.Default.Title"] = "Birds",
            ["Main.Header.Default.Subtitle"] = "Рабочее пространство приложения.",

            ["AddBird.SpeciesLabel"] = "Вид птицы",
            ["AddBird.ArrivalLabel"] = "Дата прибытия",
            ["AddBird.DescriptionLabel"] = "Описание",
            ["AddBird.DescriptionHint"] = "Описание необязательно. До 200 символов.",
            ["AddBird.OneTimeTitle"] = "Разовое содержание",
            ["AddBird.OneTimeHint"] = "Если птица прибыла и выбыла в один день, дата выбытия заполнится автоматически.",
            ["AddBird.Save"] = "Сохранить запись",

            ["Bird.CreatedLabel"] = "Создано: ",
            ["Bird.UpdatedLabel"] = "Обновлено: ",
            ["Bird.DaysSuffix"] = "дней",
            ["Bird.ArrivalMeta"] = "Прибыла",
            ["Bird.DepartureMeta"] = "Выбыла",
            ["Bird.DurationMeta"] = "Срок",
            ["Bird.StatusLabel"] = "Статус",
            ["Bird.StatusAlive"] = "Жива",
            ["Bird.StatusDead"] = "Мертва",
            ["Bird.NoDescription"] = "Описание не добавлено.",
            ["Bird.Action.Edit"] = "Редактировать запись",
            ["Bird.Action.Delete"] = "Удалить запись",
            ["Bird.Action.ConfirmDelete"] = "Подтвердить удаление",
            ["Bird.Action.CancelDelete"] = "Отменить удаление",
            ["Bird.Action.Save"] = "Сохранить изменения",
            ["Bird.Action.CancelEdit"] = "Отменить редактирование",

            ["BirdList.CountLabel"] = "Птиц: ",
            ["BirdList.CountTitle"] = "Птиц",
            ["BirdList.SearchPlaceholder"] = "Поиск по виду, дате или описанию",
            ["BirdList.Retry"] = "Повторить",
            ["BirdList.EmptyTitle"] = "Ничего не найдено",
            ["BirdList.EmptyDescription"] = "Попробуйте изменить поиск или фильтр.",
            ["BirdList.Loading"] = "Загрузка архива...",
            ["BirdList.Filter.All"] = "Показать всех",
            ["BirdList.Filter.Alive"] = "Показать только живых",
            ["BirdList.Filter.Dead"] = "Только мертвые",
            ["BirdList.Filter.Released"] = "Отпущенные",

            ["Statistics.Title"] = "Статистика по птицам",
            ["Statistics.Year"] = "Год:",
            ["Statistics.AllYears"] = "Все года",
            ["Statistics.TotalBirdsLabel"] = "Всего поймано: ",
            ["Statistics.ReleasedLabel"] = "Отпущено: ",
            ["Statistics.KilledLabel"] = "Уничтожено: ",
            ["Statistics.TopMonthLabel"] = "Самый продуктивный месяц: ",
            ["Statistics.TopWeekLabel"] = "Самая продуктивная неделя: ",
            ["Statistics.TopDayLabel"] = "Самый продуктивный день: ",
            ["Statistics.LongestBreakLabel"] = "Самый большой перерыв: ",
            ["Statistics.Tab.BySpecies"] = "По видам",
            ["Statistics.Tab.ByYears"] = "По годам",
            ["Statistics.Tab.ByMonths"] = "По месяцам",
            ["Statistics.Tab.ByKeepingDuration"] = "По длительности содержания",
            ["Statistics.Loading"] = "Загрузка...",
            ["Statistics.CountBirds"] = "{0} птиц",
            ["Statistics.LongestBreakValue"] = "{0} дней без поимок (между {1} и {2})",

            ["Settings.Title"] = "Настройки",
            ["Settings.Subtitle"] = "Центр пользовательских предпочтений. Изменения сохраняются автоматически.",
            ["Settings.Interface.Title"] = "Интерфейс",
            ["Settings.Interface.Description"] = "Здесь можно управлять языком, темой и базовым поведением интерфейса.",
            ["Settings.LanguageLabel"] = "Язык интерфейса",
            ["Settings.ThemeLabel"] = "Тема приложения",
            ["Settings.DateFormatLabel"] = "Формат даты",
            ["Settings.Theme.Graphite"] = "Графит",
            ["Settings.Theme.Steel"] = "Сталь",
            ["Settings.DateFormat.DayMonthYear"] = "31.12.2026",
            ["Settings.DateFormat.MonthDayYear"] = "12/31/2026",
            ["Settings.DateFormat.YearMonthDay"] = "2026-12-31",
            ["Settings.MotionLabel"] = "Сдержанные анимации",
            ["Settings.Notifications.Title"] = "Уведомления",
            ["Settings.Notifications.Description"] = "Можно оставить историю уведомлений и при этом убрать навязчивый индикатор новых событий.",
            ["Settings.NotificationBadgeLabel"] = "Показывать индикатор новых уведомлений",
            ["Settings.AutoExportLabel"] = "Автоэкспорт снимка",
            ["Settings.SyncStatusLabel"] = "Состояние синхронизации",
            ["Settings.Data.Title"] = "Данные",
            ["Settings.Data.Description"] = "Вручную экспортируйте текущий снимок или импортируйте JSON-файл, созданный приложением.",
            ["Settings.ExportPathLabel"] = "Путь экспорта",
            ["Settings.ExportPathButton"] = "Изменить путь",
            ["Settings.ExportLabel"] = "Экспорт данных",
            ["Settings.ExportButton"] = "Экспортировать",
            ["Settings.ImportModeLabel"] = "Режим импорта",
            ["Settings.ImportMode.Merge"] = "Объединить с текущими данными",
            ["Settings.ImportMode.Replace"] = "Полностью заменить текущие данные",
            ["Settings.ImportLabel"] = "Импорт данных",
            ["Settings.ImportButton"] = "Импортировать",
            ["Settings.Data.ExportHint"] = "Путь экспорта: {0}",
            ["Settings.Data.ExportActionHint"] = "Экспортирует текущий снимок в выбранный JSON-файл.",
            ["Settings.Data.ImportHint.Merge"] = "Импорт объединяет записи по Id: новые добавляются, совпадающие обновляются, а локальные записи вне файла не удаляются.",
            ["Settings.Data.ImportHint.Replace"] = "Импорт полностью заменяет текущий архив снимком из файла. Локальные записи, которых нет в файле, будут удалены.",
            ["Settings.ResetTitle"] = "Сброс к стандартным значениям",
            ["Settings.ResetDescription"] = "Полезно, если захочется быстро вернуть базовые параметры интерфейса.",
            ["Settings.ResetButton"] = "Сбросить",
            ["Settings.Danger.Title"] = "Опасная зона",
            ["Settings.Danger.Description"] = "Необратимые действия с данными. Перед ними лучше сделать экспорт резервной копии.",
            ["Settings.Danger.ClearTitle"] = "Очистить все записи о птицах",
            ["Settings.Danger.ClearDescription"] = "Удаляет все записи из архива, но не трогает структуру базы и настройки приложения.",
            ["Settings.Danger.ClearButton"] = "Очистить архив",
            ["Settings.Danger.ClearConfirm"] = "Да, очистить архив",
            ["Settings.Danger.ResetTitle"] = "Сбросить локальную SQLite-базу",
            ["Settings.Danger.ResetDescription"] = "Полностью пересоздаёт локальную базу данных. Используйте это только для полного сброса рабочего окружения.",
            ["Settings.Danger.ResetButton"] = "Сбросить базу",
            ["Settings.Danger.ResetConfirm"] = "Да, сбросить базу",
            ["Settings.Danger.Cancel"] = "Отмена",
            ["Settings.Danger.ConfirmClearHint"] = "Подтвердите очистку архива. Это действие нельзя отменить.",
            ["Settings.Danger.ConfirmResetHint"] = "Подтвердите полный сброс локальной SQLite-базы. Все записи будут удалены без возможности восстановления.",
            ["Settings.Danger.ResetUnavailable"] = "Полный сброс базы доступен только в локальном SQLite-режиме.",
            ["Settings.LanguageHint.Russian"] = "Русский язык включен для всего интерфейса, уведомлений и сообщений валидации.",
            ["Settings.LanguageHint.English"] = "English is now used for the interface, notifications and validation messages.",
            ["Settings.ThemeHint.Graphite"] = "Строгая графитовая палитра с нейтральным акцентом.",
            ["Settings.ThemeHint.Steel"] = "Холодная стальная палитра с более выраженным синим тоном.",
            ["Settings.DateFormatHint.DayMonthYear"] = "Сначала день, затем месяц и год. Подходит для привычного локального чтения даты.",
            ["Settings.DateFormatHint.MonthDayYear"] = "Сначала месяц, затем день и год. Удобно, если хочется американский порядок дат.",
            ["Settings.DateFormatHint.YearMonthDay"] = "Сначала год, затем месяц и день. Хорошо подходит для строгого и сортируемого формата.",
            ["Settings.ImportModeHint.Merge"] = "Безопасный режим: импорт дополняет архив и обновляет совпадающие записи, не трогая остальные.",
            ["Settings.ImportModeHint.Replace"] = "Режим восстановления снимка: текущий архив будет синхронизирован с файлом и лишние локальные записи исчезнут.",
            ["Settings.NotificationsHint.Enabled"] = "Индикатор новых уведомлений будет показываться рядом с кнопкой центра уведомлений.",
            ["Settings.NotificationsHint.Disabled"] = "Красный индикатор скрыт, но сама история уведомлений остаётся доступной.",
            ["Settings.AutoExportHint.Enabled"] = "После успешных изменений и при закрытии приложения экспортный снимок будет обновляться автоматически.",
            ["Settings.AutoExportHint.Disabled"] = "Автоэкспорт отключён. Снимок будет обновляться только вручную.",
            ["Settings.SyncStatus.Disabled"] = "Локально",
            ["Settings.SyncStatus.Syncing"] = "Синхронизация",
            ["Settings.SyncStatus.Synced"] = "Синхронизировано",
            ["Settings.SyncStatus.Paused"] = "На паузе",
            ["Settings.SyncStatus.Offline"] = "Offline",
            ["Settings.SyncStatus.Error"] = "Ошибка",
            ["Settings.SyncStatusHint.Disabled"] = "Удалённая синхронизация не настроена. Приложение работает только с локальной SQLite-базой.",
            ["Settings.SyncStatusHint.Syncing"] = "Локальные изменения сейчас отправляются в удалённый backend.",
            ["Settings.SyncStatusHint.SyncingWithLastSuccess"] = "Идёт синхронизация. Последний успешный обмен был: {0}.",
            ["Settings.SyncStatusHint.Synced"] = "Локальный архив синхронизирован с удалённым backend.",
            ["Settings.SyncStatusHint.SyncedWithTimestamp"] = "Последняя успешная синхронизация: {0}.",
            ["Settings.SyncStatusHint.Paused"] = "Автоматическая синхронизация поставлена на паузу.",
            ["Settings.SyncStatusHint.PausedWithLastSuccess"] = "Автоматическая синхронизация на паузе. Последний успешный обмен был: {0}.",
            ["Settings.SyncStatusHint.Offline"] = "Удалённый backend сейчас недоступен. Локальные изменения останутся в очереди и синхронизируются автоматически после восстановления соединения.",
            ["Settings.SyncStatusHint.Error"] = "Последняя попытка синхронизации завершилась ошибкой. Локальные изменения останутся в очереди до следующей успешной попытки.",
            ["Settings.SyncStatusHint.PendingCount"] = "В локальной очереди: {0}.",
            ["Settings.SyncStatusHint.LastError"] = "Последняя деталь: {0}",
            ["Settings.SyncMeta.PendingLabel"] = "В очереди",
            ["Settings.SyncMeta.PendingNone"] = "Нет",
            ["Settings.SyncMeta.LastSuccessLabel"] = "Последний успех",
            ["Settings.SyncMeta.Never"] = "Ещё не было",
            ["Settings.SyncAction.SyncNow"] = "Синхронизировать",
            ["Settings.SyncAction.Pause"] = "Пауза",
            ["Settings.SyncAction.Resume"] = "Возобновить",
            ["Settings.MotionHint.Enabled"] = "Сдержанный режим анимации сохранён как предпочтение и готов для будущих экранов.",
            ["Settings.MotionHint.Disabled"] = "Сейчас приложение использует стандартные мягкие анимации интерфейса.",

            ["Notification.CenterTitle"] = "Уведомления",
            ["Notification.UnreadLabel"] = "Непрочитано: ",
            ["Notification.Clear"] = "Очистить",
            ["Notification.EmptyTitle"] = "Пока пусто",
            ["Notification.EmptyDescription"] = "Здесь будет история действий и важных сообщений приложения.",
            ["Notification.New"] = "Новое",
            ["Notification.Type.Info"] = "Инфо",
            ["Notification.Type.Success"] = "Успех",
            ["Notification.Type.Warning"] = "Внимание",
            ["Notification.Type.Error"] = "Ошибка",
            ["Notification.Title.Info"] = "Информация",
            ["Notification.Title.Success"] = "Успешно",
            ["Notification.Title.Warning"] = "Внимание",
            ["Notification.Title.Error"] = "Ошибка",
            ["Notification.QuickStatus.Success"] = "Последняя операция завершилась успешно",
            ["Notification.QuickStatus.Error"] = "Последняя операция завершилась ошибкой",
            ["Notification.UndoDelete"] = "Вернуть",
            ["Notification.UndoDelete.ToolTip"] = "Отменить удаление записи",

            ["Exception.Source.UiDispatcher"] = "Диспетчер UI",
            ["Exception.Source.AppDomain"] = "Домен приложения",
            ["Exception.Source.UnobservedTask"] = "Неотслеженная задача",
            ["Exception.InvalidOperation"] = "ExceptionHandlingBehavior может обрабатывать только ответы типа Result или Result<T>. Фактический тип: {0}",
            ["Exception.NotFound"] = "{0} с ключом '{1}' не найден.",
            ["Exception.ValidationFailure"] = "Ошибка валидации: {0}",
            ["Exception.NotFoundFailure"] = "Не найдено: {0}",
            ["Exception.UnexpectedFailure"] = "Непредвиденная ошибка: {0}",
            ["Exception.OperationCanceled"] = "{0}: операция была отменена.",
            ["Exception.Timeout"] = "{0}: истекло время выполнения операции.",
            ["Exception.Network"] = "{0}: произошла сетевая ошибка. Проверьте подключение к интернету.",
            ["Exception.DatabaseConnection"] = "{0}: не удалось подключиться к базе данных.",
            ["Exception.Unexpected"] = "{0}: произошла непредвиденная ошибка.",

            ["Info.LoadingBirdData"] = "Загрузка данных о птицах...",
            ["Info.LoadedSuccessfully"] = "Данные о птицах успешно загружены.",
            ["Info.NoBirdRecordsYet"] = "Записей о птицах пока нет. Добавьте первую птицу, чтобы начать.",
            ["Info.ReloadingBirdData"] = "Повторная загрузка данных о птицах...",
            ["Info.AddingBird"] = "Добавление птицы...",
            ["Info.UpdatingBird"] = "Обновление записи о птице...",
            ["Info.UpdatedBird"] = "Птица успешно обновлена!",
            ["Info.DeletingBird"] = "Удаление птицы...",
            ["Info.DeletedBird"] = "Птица успешно удалена!",
            ["Info.DeleteRestored"] = "Удаление отменено. Запись возвращена.",
            ["Info.BirdAdded"] = "Птица успешно добавлена!",
            ["Info.ToThisDay"] = "по сегодняшний день",
            ["Info.LoadFailed"] = "Попытка {0} загрузить птиц не удалась. Повтор через {1} с.",
            ["Info.AutoExportSucceeded"] = "Автоэкспорт выполнен. Путь: {0}",
            ["Info.ExportSucceeded"] = "Экспорт выполнен. Путь: {0}",
            ["Info.ImportMergedSucceeded"] = "Импорт завершён. Обработано: {0}, добавлено: {1}, обновлено: {2}.",
            ["Info.ImportReplacedSucceeded"] = "Снимок восстановлен. Обработано: {0}, добавлено: {1}, обновлено: {2}, удалено: {3}.",
            ["Info.BirdRecordsCleared"] = "Архив очищен. Удалено записей: {0}.",
            ["Info.LocalDatabaseReset"] = "Локальная база данных сброшена.",

            ["Error.BirdLoadFailed"] = "Не удалось загрузить данные о птицах из базы данных.\nПроверьте подключение или перезапустите приложение.",
            ["Error.UnknownError"] = "Неизвестная ошибка.",
            ["Error.UnexpectedError"] = "Непредвиденная ошибка.",
            ["Error.CannotSaveBird"] = "Не удалось сохранить птицу!",
            ["Error.CannotDeleteBird"] = "Не удалось удалить птицу!",
            ["Error.CannotUpdateBird"] = "Не удалось обновить птицу!",
            ["Error.RequestCannotBeNull"] = "Запрос не может быть null.",
            ["Error.QueryCannotBeNull"] = "Query не может быть null.",
            ["Error.ConnectionStringNotFound"] = "Строка подключения к базе данных не найдена.",
            ["Error.ConnectionStringNotFoundFor"] = "Строка подключения к базе данных не найдена. Ожидалась одна из: {0}.",
            ["Error.InvalidDatabaseProvider"] = "Неподдерживаемый провайдер базы данных '{0}'. Используйте 'Sqlite' или 'Postgres'.",
            ["Error.InvalidDatabaseSeedingMode"] = "Неподдерживаемый режим сидинга '{0}'. Используйте 'None', 'SeedIfEmpty' или 'RecreateAndSeed'.",
            ["Error.ImportPathCannotBeEmpty"] = "Путь к файлу импорта не указан.",
            ["Error.ImportFileNotFound"] = "Файл импорта не найден: {0}",
            ["Error.ImportPayloadCannotBeNull"] = "Импортируемый набор данных отсутствует.",
            ["Error.InvalidImportFileFormat"] = "Не удалось разобрать файл импорта. Ожидался JSON-формат приложения Birds.",
            ["Error.UnsupportedImportVersion"] = "Файл импорта имеет неподдерживаемую версию: {0}.",
            ["Error.ImportContainsDuplicateIds"] = "Файл импорта содержит дублирующийся Id: {0}.",
            ["Error.InvalidImportedBirdName"] = "Импорт прерван: неизвестное имя птицы '{0}'.",
            ["Error.ImportFailed"] = "Не удалось импортировать данные о птицах.",
            ["Error.ExportFailed"] = "Не удалось экспортировать данные о птицах.",
            ["Error.CannotClearBirdRecords"] = "Не удалось очистить архив птиц.",
            ["Error.CannotResetLocalDatabase"] = "Не удалось сбросить локальную базу данных.",
            ["Error.FailedToDisplayErrorNotification"] = "Не удалось показать уведомление об ошибке",
            ["Error.StartupErrorTitle"] = "Ошибка запуска",
            ["Error.StartupError"] = "Во время запуска приложения произошла ошибка:\n{0}",
            ["Error.ShutdownWarningTitle"] = "Предупреждение при завершении",
            ["Error.ShutdownError"] = "Ошибка при завершении приложения:\n{0}",

            ["Validation.UnselectedBird"] = "Выберите вид птицы из списка.",
            ["Validation.LongDescription"] = "Описание слишком длинное. Максимум 200 символов.",
            ["Validation.DateIsNotSpecified"] = "Укажите дату.",
            ["Validation.InvalidDateRange"] = "Дата должна быть в диапазоне от {0:dd-MM-yyyy} до {1:dd-MM-yyyy}.",
            ["Validation.DateIsNotValid"] = "Укажите корректную дату.",
            ["Validation.DateCannotBeInTheFuture"] = "Дата не может быть из будущего (не позже {0:dd-MM-yyyy}).",
            ["Validation.DepartureLaterThenArrival"] = "Дата выбытия не может быть раньше даты прибытия ({0:dd-MM-yyyy}).",

            ["BirdName.Воробей"] = "Воробей",
            ["BirdName.Щегол"] = "Щегол",
            ["BirdName.Амадин"] = "Амадин",
            ["BirdName.Дубонос"] = "Дубонос",
            ["BirdName.Большак"] = "Большак",
            ["BirdName.Гайка"] = "Гайка",
            ["BirdName.Поползень"] = "Поползень",
            ["BirdName.Unknown"] = "Неизвестно"
        };

        private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Language.Russian"] = "Russian",
            ["Language.English"] = "English",

            ["Nav.AddBird"] = "Add bird",
            ["Nav.Archive"] = "Archive",
            ["Nav.Statistics"] = "Statistics",
            ["Nav.Settings"] = "Settings",

            ["Main.Header.AddBird.Title"] = "Add bird",
            ["Main.Header.AddBird.Subtitle"] = "A new entry with basic validation and a clean input form.",
            ["Main.Header.Archive.Title"] = "Bird archive",
            ["Main.Header.Archive.Subtitle"] = "Search, filter and edit existing entries.",
            ["Main.Header.Statistics.Title"] = "Statistics",
            ["Main.Header.Statistics.Subtitle"] = "Overview by species, dates and key metrics.",
            ["Main.Header.Settings.Title"] = "Settings",
            ["Main.Header.Settings.Subtitle"] = "Preferences for the interface and application behaviour.",
            ["Main.Header.Default.Title"] = "Birds",
            ["Main.Header.Default.Subtitle"] = "The application's workspace.",

            ["AddBird.SpeciesLabel"] = "Bird species",
            ["AddBird.ArrivalLabel"] = "Arrival date",
            ["AddBird.DescriptionLabel"] = "Description",
            ["AddBird.DescriptionHint"] = "Description is optional. Up to 200 characters.",
            ["AddBird.OneTimeTitle"] = "One-time keeping",
            ["AddBird.OneTimeHint"] = "If the bird arrived and left on the same day, the departure date will be filled automatically.",
            ["AddBird.Save"] = "Save entry",

            ["Bird.CreatedLabel"] = "Created: ",
            ["Bird.UpdatedLabel"] = "Updated: ",
            ["Bird.DaysSuffix"] = "days",
            ["Bird.ArrivalMeta"] = "Arrived",
            ["Bird.DepartureMeta"] = "Departed",
            ["Bird.DurationMeta"] = "Duration",
            ["Bird.StatusLabel"] = "Status",
            ["Bird.StatusAlive"] = "Alive",
            ["Bird.StatusDead"] = "Dead",
            ["Bird.NoDescription"] = "No description added.",
            ["Bird.Action.Edit"] = "Edit entry",
            ["Bird.Action.Delete"] = "Delete entry",
            ["Bird.Action.ConfirmDelete"] = "Confirm deletion",
            ["Bird.Action.CancelDelete"] = "Cancel deletion",
            ["Bird.Action.Save"] = "Save changes",
            ["Bird.Action.CancelEdit"] = "Cancel editing",

            ["BirdList.CountLabel"] = "Birds: ",
            ["BirdList.CountTitle"] = "Birds",
            ["BirdList.SearchPlaceholder"] = "Search by species, date or note",
            ["BirdList.Retry"] = "Retry",
            ["BirdList.EmptyTitle"] = "Nothing found",
            ["BirdList.EmptyDescription"] = "Try changing the search or filter.",
            ["BirdList.Loading"] = "Loading archive...",
            ["BirdList.Filter.All"] = "Show all",
            ["BirdList.Filter.Alive"] = "Show alive only",
            ["BirdList.Filter.Dead"] = "Dead only",
            ["BirdList.Filter.Released"] = "Released",

            ["Statistics.Title"] = "Bird statistics",
            ["Statistics.Year"] = "Year:",
            ["Statistics.AllYears"] = "All years",
            ["Statistics.TotalBirdsLabel"] = "Captured total: ",
            ["Statistics.ReleasedLabel"] = "Released: ",
            ["Statistics.KilledLabel"] = "Destroyed: ",
            ["Statistics.TopMonthLabel"] = "Most productive month: ",
            ["Statistics.TopWeekLabel"] = "Most productive week: ",
            ["Statistics.TopDayLabel"] = "Most productive day: ",
            ["Statistics.LongestBreakLabel"] = "Longest break: ",
            ["Statistics.Tab.BySpecies"] = "By species",
            ["Statistics.Tab.ByYears"] = "By years",
            ["Statistics.Tab.ByMonths"] = "By months",
            ["Statistics.Tab.ByKeepingDuration"] = "By keeping duration",
            ["Statistics.Loading"] = "Loading...",
            ["Statistics.CountBirds"] = "{0} birds",
            ["Statistics.LongestBreakValue"] = "{0} days without captures (between {1} and {2})",

            ["Settings.Title"] = "Settings",
            ["Settings.Subtitle"] = "A hub for user preferences. Changes are saved automatically.",
            ["Settings.Interface.Title"] = "Interface",
            ["Settings.Interface.Description"] = "Manage language, theme and the base interaction behaviour here.",
            ["Settings.LanguageLabel"] = "Interface language",
            ["Settings.ThemeLabel"] = "Application theme",
            ["Settings.DateFormatLabel"] = "Date format",
            ["Settings.Theme.Graphite"] = "Graphite",
            ["Settings.Theme.Steel"] = "Steel",
            ["Settings.DateFormat.DayMonthYear"] = "31.12.2026",
            ["Settings.DateFormat.MonthDayYear"] = "12/31/2026",
            ["Settings.DateFormat.YearMonthDay"] = "2026-12-31",
            ["Settings.MotionLabel"] = "Reduced motion",
            ["Settings.Notifications.Title"] = "Notifications",
            ["Settings.Notifications.Description"] = "You can keep notification history while hiding the distracting unread indicator.",
            ["Settings.NotificationBadgeLabel"] = "Show unread notification badge",
            ["Settings.AutoExportLabel"] = "Automatic snapshot export",
            ["Settings.SyncStatusLabel"] = "Cloud sync status",
            ["Settings.Data.Title"] = "Data",
            ["Settings.Data.Description"] = "Export the current snapshot manually or import a JSON file produced by the application.",
            ["Settings.ExportPathLabel"] = "Export location",
            ["Settings.ExportPathButton"] = "Change path",
            ["Settings.ExportLabel"] = "Export data",
            ["Settings.ExportButton"] = "Export",
            ["Settings.ImportModeLabel"] = "Import mode",
            ["Settings.ImportMode.Merge"] = "Merge with current data",
            ["Settings.ImportMode.Replace"] = "Replace current data completely",
            ["Settings.ImportLabel"] = "Import data",
            ["Settings.ImportButton"] = "Import",
            ["Settings.Data.ExportHint"] = "Export location: {0}",
            ["Settings.Data.ExportActionHint"] = "Exports the current snapshot to the selected JSON file.",
            ["Settings.Data.ImportHint.Merge"] = "Import merges records by Id: new entries are added, matching ones are updated, and local records outside the file remain untouched.",
            ["Settings.Data.ImportHint.Replace"] = "Import replaces the current archive with the snapshot from the file. Local records missing from the file will be removed.",
            ["Settings.ResetTitle"] = "Reset to defaults",
            ["Settings.ResetDescription"] = "Useful when you want to quickly return to the default interface settings.",
            ["Settings.ResetButton"] = "Reset",
            ["Settings.Danger.Title"] = "Danger zone",
            ["Settings.Danger.Description"] = "Irreversible data actions. It is best to export a backup before using them.",
            ["Settings.Danger.ClearTitle"] = "Clear all bird records",
            ["Settings.Danger.ClearDescription"] = "Removes every bird record from the archive while keeping the database structure and application settings intact.",
            ["Settings.Danger.ClearButton"] = "Clear archive",
            ["Settings.Danger.ClearConfirm"] = "Yes, clear archive",
            ["Settings.Danger.ResetTitle"] = "Reset local SQLite database",
            ["Settings.Danger.ResetDescription"] = "Recreates the local database from scratch. Use this only when you want a complete local reset.",
            ["Settings.Danger.ResetButton"] = "Reset database",
            ["Settings.Danger.ResetConfirm"] = "Yes, reset database",
            ["Settings.Danger.Cancel"] = "Cancel",
            ["Settings.Danger.ConfirmClearHint"] = "Confirm clearing the archive. This action cannot be undone.",
            ["Settings.Danger.ConfirmResetHint"] = "Confirm resetting the local SQLite database. All records will be removed without recovery.",
            ["Settings.Danger.ResetUnavailable"] = "Full database reset is available only when the application uses local SQLite.",
            ["Settings.LanguageHint.Russian"] = "Russian is now used for the interface, notifications and validation messages.",
            ["Settings.LanguageHint.English"] = "English is now used for the interface, notifications and validation messages.",
            ["Settings.ThemeHint.Graphite"] = "A restrained graphite palette with a neutral accent.",
            ["Settings.ThemeHint.Steel"] = "A colder steel palette with a clearer blue tone.",
            ["Settings.DateFormatHint.DayMonthYear"] = "Day comes first, then month and year. Good for a familiar local reading order.",
            ["Settings.DateFormatHint.MonthDayYear"] = "Month comes first, then day and year. Useful if you prefer the US-style order.",
            ["Settings.DateFormatHint.YearMonthDay"] = "Year comes first, then month and day. Works well for a strict sortable format.",
            ["Settings.ImportModeHint.Merge"] = "Safe mode: the import enriches the archive and updates matching records without touching the rest.",
            ["Settings.ImportModeHint.Replace"] = "Snapshot restore mode: the current archive will be synchronized with the file and extra local records will be removed.",
            ["Settings.NotificationsHint.Enabled"] = "The unread badge will be shown next to the notification center button.",
            ["Settings.NotificationsHint.Disabled"] = "The red unread badge is hidden, but the notification history stays available.",
            ["Settings.AutoExportHint.Enabled"] = "After successful changes and on application shutdown the export snapshot will be refreshed automatically.",
            ["Settings.AutoExportHint.Disabled"] = "Auto-export is disabled. The snapshot will only be updated manually.",
            ["Settings.SyncStatus.Disabled"] = "Local only",
            ["Settings.SyncStatus.Syncing"] = "Syncing",
            ["Settings.SyncStatus.Synced"] = "Synced",
            ["Settings.SyncStatus.Paused"] = "Paused",
            ["Settings.SyncStatus.Offline"] = "Offline",
            ["Settings.SyncStatus.Error"] = "Error",
            ["Settings.SyncStatusHint.Disabled"] = "Remote synchronization is not configured. The application is using only the local SQLite store.",
            ["Settings.SyncStatusHint.Syncing"] = "Local changes are currently being synchronized with the remote backend.",
            ["Settings.SyncStatusHint.SyncingWithLastSuccess"] = "Synchronization is in progress. The last successful exchange was at {0}.",
            ["Settings.SyncStatusHint.Synced"] = "The local archive is synchronized with the remote backend.",
            ["Settings.SyncStatusHint.SyncedWithTimestamp"] = "Last successful sync: {0}.",
            ["Settings.SyncStatusHint.Paused"] = "Automatic synchronization is paused.",
            ["Settings.SyncStatusHint.PausedWithLastSuccess"] = "Automatic synchronization is paused. The last successful exchange was at {0}.",
            ["Settings.SyncStatusHint.Offline"] = "The remote backend is currently unavailable. Local changes will stay queued and synchronize automatically when the connection returns.",
            ["Settings.SyncStatusHint.Error"] = "The latest synchronization attempt failed. Local changes will stay queued until the next successful attempt.",
            ["Settings.SyncStatusHint.PendingCount"] = "Queued local changes: {0}.",
            ["Settings.SyncStatusHint.LastError"] = "Latest detail: {0}",
            ["Settings.SyncMeta.PendingLabel"] = "Pending",
            ["Settings.SyncMeta.PendingNone"] = "None",
            ["Settings.SyncMeta.LastSuccessLabel"] = "Last success",
            ["Settings.SyncMeta.Never"] = "Never",
            ["Settings.SyncAction.SyncNow"] = "Sync now",
            ["Settings.SyncAction.Pause"] = "Pause",
            ["Settings.SyncAction.Resume"] = "Resume",
            ["Settings.MotionHint.Enabled"] = "Reduced motion is saved as a preference and is ready for future screens.",
            ["Settings.MotionHint.Disabled"] = "The application currently uses the default subtle interface animations.",

            ["Notification.CenterTitle"] = "Notifications",
            ["Notification.UnreadLabel"] = "Unread: ",
            ["Notification.Clear"] = "Clear",
            ["Notification.EmptyTitle"] = "Nothing here yet",
            ["Notification.EmptyDescription"] = "The history of actions and important application messages will appear here.",
            ["Notification.New"] = "New",
            ["Notification.Type.Info"] = "Info",
            ["Notification.Type.Success"] = "Success",
            ["Notification.Type.Warning"] = "Warning",
            ["Notification.Type.Error"] = "Error",
            ["Notification.Title.Info"] = "Information",
            ["Notification.Title.Success"] = "Success",
            ["Notification.Title.Warning"] = "Warning",
            ["Notification.Title.Error"] = "Error",
            ["Notification.QuickStatus.Success"] = "The latest operation completed successfully",
            ["Notification.QuickStatus.Error"] = "The latest operation failed",
            ["Notification.UndoDelete"] = "Undo",
            ["Notification.UndoDelete.ToolTip"] = "Undo deleting this entry",

            ["Exception.Source.UiDispatcher"] = "UI Dispatcher",
            ["Exception.Source.AppDomain"] = "AppDomain",
            ["Exception.Source.UnobservedTask"] = "Unobserved Task",
            ["Exception.InvalidOperation"] = "ExceptionHandlingBehavior can only handle responses of type Result or Result<T>. Actual type: {0}",
            ["Exception.NotFound"] = "{0} with key '{1}' was not found.",
            ["Exception.ValidationFailure"] = "Validation error: {0}",
            ["Exception.NotFoundFailure"] = "Not found: {0}",
            ["Exception.UnexpectedFailure"] = "Unexpected error: {0}",
            ["Exception.OperationCanceled"] = "{0}: The operation was canceled.",
            ["Exception.Timeout"] = "{0}: The operation has timed out.",
            ["Exception.Network"] = "{0}: A network error occurred. Check your internet connection.",
            ["Exception.DatabaseConnection"] = "{0}: Failed to connect to the database.",
            ["Exception.Unexpected"] = "{0}: An unexpected error has occurred.",

            ["Info.LoadingBirdData"] = "Loading bird data...",
            ["Info.LoadedSuccessfully"] = "Bird data loaded successfully.",
            ["Info.NoBirdRecordsYet"] = "No bird records yet. Add your first bird to get started.",
            ["Info.ReloadingBirdData"] = "Reloading bird data...",
            ["Info.AddingBird"] = "Adding bird...",
            ["Info.UpdatingBird"] = "Updating bird...",
            ["Info.UpdatedBird"] = "Bird updated successfully!",
            ["Info.DeletingBird"] = "Deleting bird...",
            ["Info.DeletedBird"] = "Bird deleted successfully!",
            ["Info.DeleteRestored"] = "Deletion was canceled. The record was restored.",
            ["Info.BirdAdded"] = "Bird added successfully!",
            ["Info.ToThisDay"] = "to this day",
            ["Info.LoadFailed"] = "Attempt {0} to load birds failed. Retrying in {1}s.",
            ["Info.AutoExportSucceeded"] = "Auto-export succeeded. Path: {0}",
            ["Info.ExportSucceeded"] = "Export completed. Path: {0}",
            ["Info.ImportMergedSucceeded"] = "Import completed. Processed: {0}, added: {1}, updated: {2}.",
            ["Info.ImportReplacedSucceeded"] = "Snapshot restored. Processed: {0}, added: {1}, updated: {2}, removed: {3}.",
            ["Info.BirdRecordsCleared"] = "Archive cleared. Records removed: {0}.",
            ["Info.LocalDatabaseReset"] = "Local database has been reset.",

            ["Error.BirdLoadFailed"] = "Failed to load bird data from the database.\nPlease check your connection or restart the application.",
            ["Error.UnknownError"] = "Unknown error.",
            ["Error.UnexpectedError"] = "Unexpected error.",
            ["Error.CannotSaveBird"] = "Unable to save bird!",
            ["Error.CannotDeleteBird"] = "Unable to delete bird!",
            ["Error.CannotUpdateBird"] = "Unable to update bird!",
            ["Error.RequestCannotBeNull"] = "Request cannot be null.",
            ["Error.QueryCannotBeNull"] = "Query cannot be null.",
            ["Error.ConnectionStringNotFound"] = "Database connection string not found.",
            ["Error.ConnectionStringNotFoundFor"] = "Database connection string not found. Expected one of: {0}.",
            ["Error.InvalidDatabaseProvider"] = "Unsupported database provider '{0}'. Use 'Sqlite' or 'Postgres'.",
            ["Error.InvalidDatabaseSeedingMode"] = "Unsupported database seeding mode '{0}'. Use 'None', 'SeedIfEmpty' or 'RecreateAndSeed'.",
            ["Error.ImportPathCannotBeEmpty"] = "The import file path is missing.",
            ["Error.ImportFileNotFound"] = "Import file not found: {0}",
            ["Error.ImportPayloadCannotBeNull"] = "The imported data payload is missing.",
            ["Error.InvalidImportFileFormat"] = "Unable to parse the import file. A Birds application JSON export was expected.",
            ["Error.UnsupportedImportVersion"] = "The import file uses an unsupported version: {0}.",
            ["Error.ImportContainsDuplicateIds"] = "The import file contains a duplicate Id: {0}.",
            ["Error.InvalidImportedBirdName"] = "Import aborted: unknown bird name '{0}'.",
            ["Error.ImportFailed"] = "Unable to import bird data.",
            ["Error.ExportFailed"] = "Unable to export bird data.",
            ["Error.CannotClearBirdRecords"] = "Unable to clear bird records.",
            ["Error.CannotResetLocalDatabase"] = "Unable to reset the local database.",
            ["Error.FailedToDisplayErrorNotification"] = "Failed to display error notification",
            ["Error.StartupErrorTitle"] = "Startup error",
            ["Error.StartupError"] = "An error occurred during application startup:\n{0}",
            ["Error.ShutdownWarningTitle"] = "Shutdown warning",
            ["Error.ShutdownError"] = "Error during application shutdown:\n{0}",

            ["Validation.UnselectedBird"] = "Select a bird species from the list.",
            ["Validation.LongDescription"] = "Description is too long. Maximum is 200 characters.",
            ["Validation.DateIsNotSpecified"] = "Specify a date.",
            ["Validation.InvalidDateRange"] = "The date must be between {0:dd-MM-yyyy} and {1:dd-MM-yyyy}.",
            ["Validation.DateIsNotValid"] = "Specify a valid date.",
            ["Validation.DateCannotBeInTheFuture"] = "The date cannot be in the future (no later than {0:dd-MM-yyyy}).",
            ["Validation.DepartureLaterThenArrival"] = "Departure date cannot be earlier than arrival date ({0:dd-MM-yyyy}).",

            ["BirdName.Воробей"] = "Sparrow",
            ["BirdName.Щегол"] = "Goldfinch",
            ["BirdName.Амадин"] = "Amadin",
            ["BirdName.Дубонос"] = "Hawfinch",
            ["BirdName.Большак"] = "Great tit",
            ["BirdName.Гайка"] = "Black-capped chickadee",
            ["BirdName.Поползень"] = "Nuthatch",
            ["BirdName.Unknown"] = "Unknown"
        };

        public static string Get(string key, CultureInfo? culture = null)
        {
            var dictionary = SelectDictionary(culture);
            if (dictionary.TryGetValue(key, out var value))
                return value;

            return Russian.TryGetValue(key, out var fallback)
                ? fallback
                : key;
        }

        public static string Format(string key, params object[] args)
            => string.Format(CultureInfo.CurrentCulture, Get(key), args);

        public static string Format(CultureInfo? culture, string key, params object[] args)
        {
            var actualCulture = culture ?? CultureInfo.CurrentCulture;
            return string.Format(actualCulture, Get(key, actualCulture), args);
        }

        private static IReadOnlyDictionary<string, string> SelectDictionary(CultureInfo? culture)
        {
            var effectiveCulture = culture
                ?? CultureInfo.DefaultThreadCurrentUICulture
                ?? CultureInfo.CurrentUICulture;

            var language = AppLanguages.Normalize(effectiveCulture.Name);
            return language == AppLanguages.English ? English : Russian;
        }
    }
}
