namespace Birds.Shared.Localization;

public static partial class AppText
{
    private static IReadOnlyDictionary<string, string> BuildRussian()
    {
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Language.Russian"] = "Русский",
            ["Language.English"] = "English",

            ["Nav.AddBird"] = "Добавить птицу",
            ["Nav.Archive"] = "Архив",
            ["Nav.Statistics"] = "Статистика",
            ["Nav.Settings"] = "Настройки",

            ["Main.Header.AddBird.Title"] = "Добавление птицы",
            ["Main.Header.AddBird.Subtitle"] = "Новая запись с базовой валидацией и чистой формой ввода.",
            ["Main.Header.Archive.Title"] = "Архив птиц",
            ["Main.Header.Archive.Subtitle"] = "Поиск, фильтрация и редактирование существующих записей.",
            ["Main.Header.Statistics.Title"] = "Статистика",
            ["Main.Header.Statistics.Subtitle"] = "Сводка по видам, датам и ключевым метрикам.",
            ["Main.Header.Settings.Title"] = "Настройки",
            ["Main.Header.Settings.Subtitle"] = "Пользовательские предпочтения интерфейса и поведения приложения.",
            ["Main.Header.Default.Title"] = "Birds",
            ["Main.Header.Default.Subtitle"] = "Рабочее пространство приложения.",

            ["AddBird.SpeciesLabel"] = "Вид птицы",
            ["AddBird.ArrivalLabel"] = "Дата прибытия",
            ["AddBird.DescriptionLabel"] = "Описание",
            ["AddBird.DescriptionHint"] = "Описание необязательно. До 200 символов.",
            ["AddBird.OneTimeTitle"] = "Разовое содержание",
            ["AddBird.OneTimeHint"] = "Если птица прибыла и выбыла в один день, дата выбытия заполнится автоматически.",
            ["AddBird.Save"] = "Сохранить запись",

            ["Bird.CreatedLabel"] = "Создано: ",
            ["Bird.UpdatedLabel"] = "Обновлено: ",
            ["Bird.DaysSuffix"] = "дней",
            ["Bird.ArrivalMeta"] = "Прибыла",
            ["Bird.DepartureMeta"] = "Выбыла",
            ["Bird.DurationMeta"] = "Срок",
            ["Bird.StatusLabel"] = "Статус",
            ["Bird.StatusAlive"] = "Жива",
            ["Bird.StatusDead"] = "Мертва",
            ["Bird.NoDescription"] = "Описание не добавлено.",
            ["Bird.Action.Edit"] = "Редактировать запись",
            ["Bird.Action.Delete"] = "Удалить запись",
            ["Bird.Action.ConfirmDelete"] = "Подтвердить удаление",
            ["Bird.Action.CancelDelete"] = "Отменить удаление",
            ["Bird.Action.Save"] = "Сохранить изменения",
            ["Bird.Action.CancelEdit"] = "Отменить редактирование",

            ["BirdList.CountLabel"] = "Птиц: ",
            ["BirdList.CountTitle"] = "Птиц",
            ["BirdList.SearchPlaceholder"] = "Поиск по виду, дате или описанию",
            ["BirdList.Retry"] = "Повторить",
            ["BirdList.EmptyTitle"] = "Ничего не найдено",
            ["BirdList.EmptyDescription"] = "Попробуйте изменить поиск или фильтр.",
            ["BirdList.Loading"] = "Загрузка архива...",
            ["BirdList.Filter.All"] = "Показать всех",
            ["BirdList.Filter.Alive"] = "Показать только живых",
            ["BirdList.Filter.Dead"] = "Только мертвые",
            ["BirdList.Filter.Released"] = "Отпущенные",

            ["Statistics.Title"] = "Статистика по птицам",
            ["Statistics.Year"] = "Год:",
            ["Statistics.AllYears"] = "Все года",
            ["Statistics.TotalBirdsLabel"] = "Всего поймано: ",
            ["Statistics.ReleasedLabel"] = "Отпущено: ",
            ["Statistics.KilledLabel"] = "Уничтожено: ",
            ["Statistics.TopMonthLabel"] = "Самый продуктивный месяц: ",
            ["Statistics.TopWeekLabel"] = "Самая продуктивная неделя: ",
            ["Statistics.TopDayLabel"] = "Самый продуктивный день: ",
            ["Statistics.LongestBreakLabel"] = "Самый большой перерыв: ",
            ["Statistics.OverviewTitle"] = "Обзор статистики",
            ["Statistics.FilterSummary.All"] =
                "Показывается общая картина по всему архиву. При желании её можно сузить до конкретного года.",
            ["Statistics.FilterSummary.Year"] = "Показывается статистика только за {0} год.",
            ["Statistics.Card.Total"] = "Всего записей в выборке",
            ["Statistics.Card.Alive"] = "Сейчас под наблюдением",
            ["Statistics.Card.Released"] = "Отпущены",
            ["Statistics.Card.Dead"] = "Мёртвые",
            ["Statistics.Card.ArrivalsLast30Days"] = "Поступило за 30 дней",
            ["Statistics.Card.DeparturesLast30Days"] = "Выбыло за 30 дней",
            ["Statistics.Card.PeakConcurrent"] = "Пиково под наблюдением",
            ["Statistics.Card.MedianKeeping"] = "Медианный срок",
            ["Statistics.Section.Species.Title"] = "Распределение по видам",
            ["Statistics.Section.Species.Description"] = "Какие виды чаще всего встречаются в текущей выборке.",
            ["Statistics.Section.Highlights.Title"] = "Ключевые наблюдения",
            ["Statistics.Section.Highlights.Description"] =
                "Короткая выжимка по пиковым периодам и средней длительности содержания.",
            ["Statistics.Section.OverviewBreakDescription"] =
                "Самый заметный промежуток без новых поступлений в архиве.",
            ["Statistics.Section.Months.Title"] = "Поступления по месяцам",
            ["Statistics.Section.Months.Description"] = "Помесячная активность внутри текущей выборки.",
            ["Statistics.Section.Departures.Title"] = "Выбытия по месяцам",
            ["Statistics.Section.Departures.Description"] =
                "Как распределяются выбытия внутри текущей выборки по месяцам.",
            ["Statistics.Section.Years.Title"] = "Обзор по годам",
            ["Statistics.Section.Years.Description"] = "Сколько записей приходится на каждый год во всём архиве.",
            ["Statistics.Section.Keeping.Title"] = "Максимальная длительность содержания",
            ["Statistics.Section.Keeping.Description"] =
                "Самый долгий срок содержания для каждого вида в текущей выборке.",
            ["Statistics.Highlight.AverageKeeping"] = "Средний срок содержания",
            ["Statistics.Highlight.TopMonth"] = "Пиковый месяц",
            ["Statistics.Highlight.TopWeek"] = "Пиковая неделя",
            ["Statistics.Highlight.TopDay"] = "Пиковый день",
            ["Statistics.Highlight.LongestBreak"] = "Самый длинный перерыв",
            ["Statistics.Highlight.LongestActiveKeeping"] = "Самый долгий текущий кейс",
            ["Statistics.AverageKeepingValue"] = "В среднем {0} дней",
            ["Statistics.MedianKeepingValue"] = "Медиана {0} дней",
            ["Statistics.LongestActiveKeepingValue"] = "{0} — {1} дней с {2}",
            ["Statistics.EmptyTitle"] = "Статистика пока пуста",
            ["Statistics.EmptyDescription"] =
                "В этой выборке ещё нет записей. Попробуйте выбрать другой год или добавить птиц в архив.",
            ["Statistics.Tab.Overview"] = "Обзор",
            ["Statistics.Tab.Distribution"] = "Распределение",
            ["Statistics.Tab.Keeping"] = "Содержание",
            ["Statistics.Tab.BySpecies"] = "По видам",
            ["Statistics.Tab.ByYears"] = "По годам",
            ["Statistics.Tab.ByMonths"] = "По месяцам",
            ["Statistics.Tab.ByKeepingDuration"] = "По длительности содержания",
            ["Statistics.Loading"] = "Загрузка...",
            ["Statistics.CountBirds"] = "{0} птиц",
            ["Statistics.LongestBreakValue"] = "{0} дней без поимок (между {1} и {2})",

            ["Settings.Title"] = "Настройки",
            ["Settings.Subtitle"] = "Центр пользовательских предпочтений. Изменения сохраняются автоматически.",
            ["Settings.Interface.Title"] = "Интерфейс",
            ["Settings.Interface.Description"] = "Здесь можно управлять языком, темой и базовым поведением интерфейса.",
            ["Settings.LanguageLabel"] = "Язык интерфейса",
            ["Settings.ThemeLabel"] = "Тема приложения",
            ["Settings.DateFormatLabel"] = "Формат даты",
            ["Settings.Theme.Graphite"] = "Графит",
            ["Settings.Theme.Steel"] = "Сталь",
            ["Settings.DateFormat.DayMonthYear"] = "31.12.2026",
            ["Settings.DateFormat.MonthDayYear"] = "12/31/2026",
            ["Settings.DateFormat.YearMonthDay"] = "2026-12-31",
            ["Settings.Notifications.Title"] = "Уведомления",
            ["Settings.Notifications.Description"] =
                "Можно оставить историю уведомлений и при этом убрать навязчивый индикатор новых событий.",
            ["Settings.NotificationBadgeLabel"] = "Показывать индикатор новых уведомлений",
            ["Settings.SyncIndicatorLabel"] = "Показывать плашку синхронизации",
            ["Settings.AutoExportLabel"] = "Автоэкспорт снимка",
            ["Settings.SyncStatusLabel"] = "Состояние синхронизации",
            ["Settings.Data.Title"] = "Данные",
            ["Settings.Data.Description"] =
                "Вручную экспортируйте текущий снимок или импортируйте JSON-файл, созданный приложением.",
            ["Settings.ExportPathLabel"] = "Путь экспорта",
            ["Settings.ExportFileButton"] = "Открыть файл",
            ["Settings.ExportFolderButton"] = "Открыть папку",
            ["Settings.ExportPathButton"] = "Изменить путь",
            ["Settings.ExportLabel"] = "Экспорт данных",
            ["Settings.ExportButton"] = "Экспортировать",
            ["Settings.ImportModeLabel"] = "Режим импорта",
            ["Settings.ImportMode.Merge"] = "Объединить с текущими данными",
            ["Settings.ImportMode.Replace"] = "Полностью заменить текущие данные",
            ["Settings.SyncIntervalLabel"] = "Обычный интервал синхронизации",
            ["Settings.SyncIntervalOption.FiveSeconds"] = "Каждые 5 секунд",
            ["Settings.SyncIntervalOption.TenSeconds"] = "Каждые 10 секунд",
            ["Settings.SyncIntervalOption.ThirtySeconds"] = "Каждые 30 секунд",
            ["Settings.SyncIntervalOption.OneMinute"] = "Каждую минуту",
            ["Settings.ImportLabel"] = "Импорт данных",
            ["Settings.ImportButton"] = "Импортировать",
            ["Settings.Data.ExportHint"] = "Путь экспорта: {0}",
            ["Settings.Data.ExportActionHint"] = "Экспортирует текущий снимок в выбранный JSON-файл.",
            ["Settings.Data.ImportHint.Merge"] =
                "Импорт объединяет записи по Id: новые добавляются, совпадающие обновляются, а локальные записи вне файла не удаляются.",
            ["Settings.Data.ImportHint.Replace"] =
                "Импорт полностью заменяет текущий архив снимком из файла. Локальные записи, которых нет в файле, будут удалены.",
            ["Settings.ResetTitle"] = "Сброс к стандартным значениям",
            ["Settings.ResetDescription"] = "Полезно, если захочется быстро вернуть базовые параметры интерфейса.",
            ["Settings.ResetButton"] = "Сбросить",
            ["Settings.Danger.Title"] = "Опасная зона",
            ["Settings.Danger.Description"] =
                "Необратимые действия с данными. Перед ними лучше сделать экспорт резервной копии.",
            ["Settings.Danger.ClearTitle"] = "Очистить все записи о птицах",
            ["Settings.Danger.ClearDescription"] =
                "Удаляет все записи из архива, но не трогает структуру базы и настройки приложения.",
            ["Settings.Danger.ClearButton"] = "Очистить архив",
            ["Settings.Danger.ClearConfirm"] = "Да, очистить архив",
            ["Settings.Danger.ResetTitle"] = "Сбросить локальную SQLite-базу",
            ["Settings.Danger.ResetDescription"] =
                "Полностью пересоздаёт локальную базу данных. Используйте это только для полного сброса рабочего окружения.",
            ["Settings.Danger.ResetButton"] = "Сбросить базу",
            ["Settings.Danger.ResetConfirm"] = "Да, сбросить базу",
            ["Settings.Danger.Cancel"] = "Отмена",
            ["Settings.Danger.ConfirmClearHint"] = "Подтвердите очистку архива. Это действие нельзя отменить.",
            ["Settings.Danger.ConfirmResetHint"] =
                "Подтвердите полный сброс локальной SQLite-базы. Все записи будут удалены без возможности восстановления.",
            ["Settings.Danger.ResetUnavailable"] = "Полный сброс базы доступен только в локальном SQLite-режиме.",
            ["Settings.LanguageHint.Russian"] =
                "Русский язык включен для всего интерфейса, уведомлений и сообщений валидации.",
            ["Settings.LanguageHint.English"] =
                "English is now used for the interface, notifications and validation messages.",
            ["Settings.ThemeHint.Graphite"] = "Строгая графитовая палитра с нейтральным акцентом.",
            ["Settings.ThemeHint.Steel"] = "Холодная стальная палитра с более выраженным синим тоном.",
            ["Settings.DateFormatHint.DayMonthYear"] =
                "Сначала день, затем месяц и год. Подходит для привычного локального чтения даты.",
            ["Settings.DateFormatHint.MonthDayYear"] =
                "Сначала месяц, затем день и год. Удобно, если хочется американский порядок дат.",
            ["Settings.DateFormatHint.YearMonthDay"] =
                "Сначала год, затем месяц и день. Хорошо подходит для строгого и сортируемого формата.",
            ["Settings.ImportModeHint.Merge"] =
                "Безопасный режим: импорт дополняет архив и обновляет совпадающие записи, не трогая остальные.",
            ["Settings.ImportModeHint.Replace"] =
                "Режим восстановления снимка: текущий архив будет синхронизирован с файлом и лишние локальные записи исчезнут.",
            ["Settings.SyncIntervalHint"] =
                "Управляет тем, как часто приложение выполняет обычные фоновые проверки синхронизации, когда remote backend доступен и работает штатно. Текущий пресет: {0}.",
            ["Settings.SyncIntervalFixedHint"] =
                "Защитные интервалы остаются фиксированными: после успешных изменений — 3 сек, на паузе — 15 сек, backend недоступен — 20 сек, повтор после ошибки — 30 сек.",
            ["Settings.RemoteSyncConfig.Title"] = "Подключение к PostgreSQL",
            ["Settings.RemoteSyncConfig.Description"] =
                "Настройте необязательный PostgreSQL backend для облачной синхронизации. Пароль хранится в профиле текущего пользователя Windows, а не в preferences.json.",
            ["Settings.RemoteSyncConfig.Enable"] = "Включить remote sync",
            ["Settings.RemoteSyncConfig.Host"] = "Host",
            ["Settings.RemoteSyncConfig.Port"] = "Порт",
            ["Settings.RemoteSyncConfig.Database"] = "База данных",
            ["Settings.RemoteSyncConfig.Username"] = "Пользователь",
            ["Settings.RemoteSyncConfig.Password"] = "Пароль",
            ["Settings.RemoteSyncConfig.PasswordSaved"] =
                "Если оставить поле пустым, будет использован сохранённый пароль.",
            ["Settings.RemoteSyncConfig.Save"] = "Сохранить подключение",
            ["Settings.RemoteSyncConfig.Test"] = "Проверить подключение",
            ["Settings.RemoteSyncConfig.DisabledHint"] =
                "Remote sync выключен. Сохранённые параметры подключения останутся на месте, чтобы его можно было включить позже.",
            ["Settings.NotificationsHint.Enabled"] =
                "Индикатор новых уведомлений будет показываться рядом с кнопкой центра уведомлений.",
            ["Settings.NotificationsHint.Disabled"] =
                "Красный индикатор скрыт, но сама история уведомлений остаётся доступной.",
            ["Settings.SyncIndicatorHint.Enabled"] =
                "Плашка синхронизации будет показываться рядом с центром уведомлений.",
            ["Settings.SyncIndicatorHint.Disabled"] =
                "Плашка синхронизации скрыта, но подробный статус остаётся доступным в настройках.",
            ["Settings.SyncIndicatorHint.Enabled"] =
                "Плашка состояния синхронизации будет показываться рядом с центром уведомлений.",
            ["Settings.SyncIndicatorHint.Disabled"] =
                "Плашка состояния синхронизации скрыта, но подробный статус остаётся доступным в настройках.",
            ["Settings.AutoExportHint.Enabled"] =
                "После успешных изменений и при закрытии приложения экспортный снимок будет обновляться автоматически.",
            ["Settings.AutoExportHint.Disabled"] = "Автоэкспорт отключён. Снимок будет обновляться только вручную.",
            ["Settings.SyncStatus.Disabled"] = "Локально",
            ["Settings.SyncStatus.Syncing"] = "Синхронизация",
            ["Settings.SyncStatus.Synced"] = "Синхронизировано",
            ["Settings.SyncStatus.Paused"] = "На паузе",
            ["Settings.SyncStatus.Offline"] = "Оффлайн",
            ["Settings.SyncStatus.Error"] = "Ошибка",
            ["Settings.SyncStatusHint.Disabled"] =
                "Удалённая синхронизация не настроена. Приложение работает только с локальной SQLite-базой.",
            ["Settings.SyncStatusHint.Syncing"] = "Локальные изменения сейчас отправляются в удалённый backend.",
            ["Settings.SyncStatusHint.SyncingWithLastSuccess"] =
                "Идёт синхронизация. Последний успешный обмен был: {0}.",
            ["Settings.SyncStatusHint.Synced"] = "Локальный архив синхронизирован с удалённым backend.",
            ["Settings.SyncStatusHint.SyncedWithTimestamp"] = "Последняя успешная синхронизация: {0}.",
            ["Settings.SyncStatusHint.RemoteEmpty"] =
                "Удалённый backend доступен, но сейчас не содержит ни одной записи о птицах.",
            ["Settings.SyncStatusHint.Paused"] = "Автоматическая синхронизация поставлена на паузу.",
            ["Settings.SyncStatusHint.PausedWithLastSuccess"] =
                "Автоматическая синхронизация на паузе. Последний успешный обмен был: {0}.",
            ["Settings.SyncStatusHint.Offline"] =
                "Удалённый backend сейчас недоступен. Локальные изменения останутся в очереди и синхронизируются автоматически после восстановления соединения.",
            ["Settings.SyncStatusHint.Error"] =
                "Последняя попытка синхронизации завершилась ошибкой. Локальные изменения останутся в очереди до следующей успешной попытки.",
            ["Settings.SyncStatusHint.PendingCount"] = "В локальной очереди: {0}.",
            ["Settings.SyncStatusHint.LastError"] = "Последняя деталь: {0}",
            ["Settings.SyncStatus.ErrorDetailTitle"] = "Проблема с подключением",
            ["Settings.SyncMeta.PendingLabel"] = "В очереди",
            ["Settings.SyncMeta.PendingNone"] = "Нет",
            ["Settings.SyncMeta.LastSuccessLabel"] = "Последний успех",
            ["Settings.SyncMeta.Never"] = "Ещё не было",
            ["Settings.SyncMeta.RemoteStateLabel"] = "Remote-данные",
            ["Settings.SyncMeta.RemoteStateLoading"] = "Загрузка...",
            ["Settings.SyncMeta.RemoteStateUnknown"] = "Неизвестно",
            ["Settings.SyncMeta.RemoteStateEmpty"] = "Пусто",
            ["Settings.SyncMeta.RemoteStateHasData"] = "Есть данные",
            ["Settings.SyncMeta.RemoteStateHasDataCount"] = "{0} записей",
            ["Settings.SyncMeta.RecentActivityLabel"] = "Последняя активность",
            ["Settings.SyncMeta.RecentActivityEmpty"] = "Событий синхронизации в этой сессии ещё не было.",
            ["Settings.SyncMeta.RecentActivityExpand"] = "Показать",
            ["Settings.SyncMeta.RecentActivityCollapse"] = "Скрыть",
            ["Settings.SyncWarning.RemoteEmptyTitle"] = "Удалённая база сейчас пуста",
            ["Settings.SyncWarning.RemoteEmptyDescription"] =
                "Локальный архив уже содержит записи, а подключённый remote backend пока пуст. Если текущая локальная база является источником истины, залейте текущий локальный снимок в remote.",
            ["Settings.SyncAction.SyncNow"] = "Синхронизировать",
            ["Settings.SyncAction.Pause"] = "Пауза",
            ["Settings.SyncAction.Resume"] = "Возобновить",
            ["Settings.SyncAction.UploadTitle"] = "Залить локальный снимок в remote",
            ["Settings.SyncAction.UploadDescription"] =
                "Полностью заменяет удалённый backend текущим состоянием локального SQLite-архива. Удалённые данные, которых нет локально, будут перезаписаны.",
            ["Settings.SyncAction.UploadButton"] = "Залить снимок",
            ["Settings.SyncAction.UploadConfirmHint"] =
                "Подтвердите загрузку текущего локального снимка. Удалённый backend будет полностью заменён текущими данными локального SQLite.",
            ["Settings.SyncAction.UploadConfirm"] = "Да, залить локальный снимок",
            ["Settings.SyncAction.RedownloadTitle"] = "Перекачать удалённый снимок",
            ["Settings.SyncAction.RedownloadDescription"] =
                "Полностью заменяет локальный SQLite-снимок текущими данными из удалённого backend. Локальные несинхронизированные изменения будут потеряны.",
            ["Settings.SyncAction.RedownloadButton"] = "Перекачать",
            ["Settings.SyncAction.RedownloadConfirmHint"] =
                "Подтвердите повторную загрузку удалённого снимка. Локальный SQLite-снимок будет полностью заменён текущими удалёнными данными.",
            ["Settings.SyncAction.RedownloadConfirm"] = "Да, перекачать снимок",
            ["Settings.SyncRecent.SyncedProcessed"] = "Применено изменений: {0}.",
            ["Settings.SyncRecent.SyncedIdle"] = "Цикл синхронизации завершился без новых изменений.",
            ["Settings.SyncRecent.Paused"] = "Автоматическая синхронизация поставлена на паузу.",
            ["Settings.SyncRecent.Offline"] = "Удалённый backend временно недоступен.",
            ["Settings.SyncRecent.Error"] = "Последняя попытка завершилась ошибкой.",
            ["Settings.SyncRecent.LocalOnly"] = "Приложение работает только с локальным хранилищем.",
            ["Notification.CenterTitle"] = "Уведомления",
            ["Notification.UnreadLabel"] = "Непрочитано: ",
            ["Notification.Clear"] = "Очистить",
            ["Notification.EmptyTitle"] = "Пока пусто",
            ["Notification.EmptyDescription"] = "Здесь будет история действий и важных сообщений приложения.",
            ["Notification.New"] = "Новое",
            ["Notification.Type.Info"] = "Инфо",
            ["Notification.Type.Success"] = "Успех",
            ["Notification.Type.Warning"] = "Внимание",
            ["Notification.Type.Error"] = "Ошибка",
            ["Notification.Title.Info"] = "Информация",
            ["Notification.Title.Success"] = "Успешно",
            ["Notification.Title.Warning"] = "Внимание",
            ["Notification.Title.Error"] = "Ошибка",
            ["Notification.QuickStatus.Success"] = "Последняя операция завершилась успешно",
            ["Notification.QuickStatus.Error"] = "Последняя операция завершилась ошибкой",
            ["Notification.UndoDelete"] = "Вернуть",
            ["Notification.UndoDelete.ToolTip"] = "Отменить удаление записи",

            ["Exception.Source.UiDispatcher"] = "Диспетчер UI",
            ["Exception.Source.AppDomain"] = "Домен приложения",
            ["Exception.Source.UnobservedTask"] = "Неотслеженная задача",
            ["Exception.InvalidOperation"] =
                "ExceptionHandlingBehavior может обрабатывать только ответы типа Result или Result<T>. Фактический тип: {0}",
            ["Exception.NotFound"] = "{0} с ключом '{1}' не найден.",
            ["Exception.ValidationFailure"] = "Ошибка валидации: {0}",
            ["Exception.NotFoundFailure"] = "Не найдено: {0}",
            ["Exception.UnexpectedFailure"] = "Непредвиденная ошибка: {0}",
            ["Exception.OperationCanceled"] = "{0}: операция была отменена.",
            ["Exception.Timeout"] = "{0}: истекло время выполнения операции.",
            ["Exception.Network"] = "{0}: произошла сетевая ошибка. Проверьте подключение к интернету.",
            ["Exception.DatabaseConnection"] = "{0}: не удалось подключиться к базе данных.",
            ["Exception.Unexpected"] = "{0}: произошла непредвиденная ошибка.",

            ["Info.LoadingBirdData"] = "Загрузка данных о птицах...",
            ["Info.LoadedSuccessfully"] = "Данные о птицах успешно загружены.",
            ["Info.NoBirdRecordsYet"] = "Записей о птицах пока нет. Добавьте первую птицу, чтобы начать.",
            ["Info.ReloadingBirdData"] = "Повторная загрузка данных о птицах...",
            ["Info.AddingBird"] = "Добавление птицы...",
            ["Info.UpdatingBird"] = "Обновление записи о птице...",
            ["Info.UpdatedBird"] = "Птица успешно обновлена!",
            ["Info.DeletingBird"] = "Удаление птицы...",
            ["Info.DeletedBird"] = "Птица успешно удалена!",
            ["Info.DeleteRestored"] = "Удаление отменено. Запись возвращена.",
            ["Info.BirdAdded"] = "Птица успешно добавлена!",
            ["Info.ToThisDay"] = "по сегодняшний день",
            ["Info.LoadFailed"] = "Попытка {0} загрузить птиц не удалась. Повтор через {1} с.",
            ["Info.AutoExportSucceeded"] = "Автоэкспорт выполнен. Путь: {0}",
            ["Info.ExportSucceeded"] = "Экспорт выполнен. Путь: {0}",
            ["Info.ImportMergedSucceeded"] = "Импорт завершён. Обработано: {0}, добавлено: {1}, обновлено: {2}.",
            ["Info.ImportReplacedSucceeded"] =
                "Снимок восстановлен. Обработано: {0}, добавлено: {1}, обновлено: {2}, удалено: {3}.",
            ["Info.BirdRecordsCleared"] = "Архив очищен. Удалено записей: {0}.",
            ["Info.LocalDatabaseReset"] = "Локальная база данных сброшена.",
            ["Info.RemoteSnapshotUploaded"] =
                "Удалённый backend заменён текущими данными локального SQLite.",
            ["Info.RemoteSnapshotRedownloaded"] = "Локальный SQLite-снимок восстановлен из удалённого backend.",
            ["Info.SyncConflictResolved"] =
                "\u0421\u0438\u043D\u0445\u0440\u043E\u043D\u0438\u0437\u0430\u0446\u0438\u044F \u0440\u0430\u0437\u0440\u0435\u0448\u0438\u043B\u0430 {0} \u043A\u043E\u043D\u0444\u043B\u0438\u043A\u0442(\u043E\u0432) \u0432 \u043F\u043E\u043B\u044C\u0437\u0443 \u0431\u043E\u043B\u0435\u0435 \u043D\u043E\u0432\u043E\u0439 \u0443\u0434\u0430\u043B\u0451\u043D\u043D\u043E\u0439 \u0432\u0435\u0440\u0441\u0438\u0438.",
            ["Info.RemoteSyncSettingsSaved"] = "Настройки remote sync сохранены.",
            ["Info.RemoteSyncConnectionSucceeded"] = "Подключение к PostgreSQL успешно проверено.",

            ["Error.BirdLoadFailed"] =
                "Не удалось загрузить данные о птицах из базы данных.\nПроверьте подключение или перезапустите приложение.",
            ["Error.UnknownError"] = "Неизвестная ошибка.",
            ["Error.UnexpectedError"] = "Непредвиденная ошибка.",
            ["Error.CannotSaveBird"] = "Не удалось сохранить птицу!",
            ["Error.CannotDeleteBird"] = "Не удалось удалить птицу!",
            ["Error.CannotUpdateBird"] = "Не удалось обновить птицу!",
            ["Error.BirdConcurrencyConflict"] =
                "Эта птица была изменена другой операцией. Перезагрузите данные и попробуйте снова.",
            ["Error.RequestCannotBeNull"] = "Запрос не может быть null.",
            ["Error.QueryCannotBeNull"] = "Query не может быть null.",
            ["Error.ConnectionStringNotFound"] = "Строка подключения к базе данных не найдена.",
            ["Error.ConnectionStringNotFoundFor"] =
                "Строка подключения к базе данных не найдена. Ожидалась одна из: {0}.",
            ["Error.RemoteSyncConfigurationMissing"] =
                "Удалённая синхронизация включена, но строка подключения PostgreSQL не настроена.",
            ["Error.RemoteSyncMissingEnvironmentVariables"] =
                "Удалённая синхронизация включена, но не заданы обязательные переменные окружения: {0}.",
            ["Error.RemoteSyncHostMissing"] = "Укажите host для remote sync.",
            ["Error.RemoteSyncPortInvalid"] = "Порт remote sync должен быть от 1 до 65535.",
            ["Error.RemoteSyncDatabaseMissing"] = "Укажите имя базы данных для remote sync.",
            ["Error.RemoteSyncUsernameMissing"] = "Укажите пользователя для remote sync.",
            ["Error.RemoteSyncPasswordMissing"] = "Укажите пароль для remote sync.",
            ["Error.RemoteSyncConnectionTestFailed"] =
                "Не удалось подключиться к удалённому PostgreSQL backend. Проверьте параметры подключения.",
            ["Error.RemoteSyncConnectionFailedWithDetail"] =
                "Не удалось подключиться к удалённому PostgreSQL backend. Проверьте параметры подключения. Детали: {0}",
            ["Error.RemoteSyncSettingsSaveFailed"] = "Не удалось сохранить настройки remote sync.",
            ["Error.InvalidDatabaseProvider"] =
                "Неподдерживаемый провайдер базы данных '{0}'. Используйте 'Sqlite' или 'Postgres'.",
            ["Error.InvalidDatabaseSeedingMode"] =
                "Неподдерживаемый режим сидинга '{0}'. Используйте 'None', 'SeedIfEmpty' или 'RecreateAndSeed'.",
            ["Error.ImportPathCannotBeEmpty"] = "Путь к файлу импорта не указан.",
            ["Error.ImportFileNotFound"] = "Файл импорта не найден: {0}",
            ["Error.ImportPayloadCannotBeNull"] = "Импортируемый набор данных отсутствует.",
            ["Error.InvalidImportFileFormat"] =
                "Не удалось разобрать файл импорта. Ожидался JSON-формат приложения Birds.",
            ["Error.UnsupportedImportVersion"] = "Файл импорта имеет неподдерживаемую версию: {0}.",
            ["Error.ImportContainsDuplicateIds"] = "Файл импорта содержит дублирующийся Id: {0}.",
            ["Error.InvalidImportedBirdName"] = "Импорт прерван: неизвестное имя птицы '{0}'.",
            ["Error.ImportFailed"] = "Не удалось импортировать данные о птицах.",
            ["Error.ImportValidationFailed"] = "Импорт прерван: архив содержит некорректные данные о птицах.",
            ["Error.ImportTransactionFailed"] =
                "Не удалось применить импорт. Текущий архив не был частично изменён.",
            ["Error.InvalidImportedBirdSpecies"] = "Импорт прерван: неизвестное значение вида птицы.",
            ["Error.ExportFailed"] = "Не удалось экспортировать данные о птицах.",
            ["Error.CannotOpenExportFile"] = "Не удалось открыть файл экспорта.",
            ["Error.CannotOpenExportFolder"] = "Не удалось открыть папку экспорта.",
            ["Error.CannotClearBirdRecords"] = "Не удалось очистить архив птиц.",
            ["Error.CannotResetLocalDatabase"] = "Не удалось сбросить локальную базу данных.",
            ["Error.CannotUploadLocalSnapshotToRemote"] =
                "Не удалось заменить удалённый backend данными локального SQLite.",
            ["Error.CannotRedownloadRemoteSnapshot"] =
                "Не удалось восстановить локальный снимок из удалённого backend.",
            ["Error.FailedToDisplayErrorNotification"] = "Не удалось показать уведомление об ошибке",
            ["Error.StartupErrorTitle"] = "Ошибка запуска",
            ["Error.StartupError"] = "Во время запуска приложения произошла ошибка:\n{0}",
            ["Error.StartupFailure"] =
                "Приложение не смогло безопасно запуститься. Ошибка записана в лог-файл.\n\nПапка логов: {0}",
            ["Error.GlobalCrashMessage"] =
                "Что-то пошло не так. Ошибка записана в лог-файл.\n\nПапка логов: {0}",
            ["Error.ShutdownWarningTitle"] = "Предупреждение при завершении",
            ["Error.ShutdownError"] = "Ошибка при завершении приложения:\n{0}",
            ["Error.ShutdownFailure"] =
                "При завершении приложения произошла ошибка. Подробности записаны в лог-файл.\n\nПапка логов: {0}",

            ["Validation.UnselectedBird"] = "Выберите вид птицы из списка.",
            ["Validation.LongDescription"] = "Описание слишком длинное. Максимум 200 символов.",
            ["Validation.DateIsNotSpecified"] = "Укажите дату.",
            ["Validation.InvalidDateRange"] = "Дата должна быть в диапазоне от {0:dd-MM-yyyy} до {1:dd-MM-yyyy}.",
            ["Validation.DateIsNotValid"] = "Укажите корректную дату.",
            ["Validation.DateCannotBeInTheFuture"] = "Дата не может быть из будущего (не позже {0:dd-MM-yyyy}).",
            ["Validation.DepartureLaterThenArrival"] =
                "Дата выбытия не может быть раньше даты прибытия ({0:dd-MM-yyyy}).",

            ["BirdName.Sparrow"] = "Воробей",
            ["BirdName.Goldfinch"] = "Щегол",
            ["BirdName.Amadin"] = "Амадин",
            ["BirdName.Hawfinch"] = "Дубонос",
            ["BirdName.GreatTit"] = "Большак",
            ["BirdName.BlackCappedChickadee"] = "Гайка",
            ["BirdName.Nuthatch"] = "Поползень",
            ["BirdName.Unknown"] = "Неизвестно"
        };
    }
}
